// Promo film — the Third Place Club Edition and the Club Administrator Academy in
// the Education OS: designed for the needs of Boys & Girls Clubs and organisations
// like them, with no affiliation, endorsement or contact claimed.
//   NODE_PATH=$(npm root -g) node tools/film/orgs/club.js
const { run, app } = require('../film');
const sec = (view, text) => `[...document.querySelectorAll('#v-${view} h2')].find(h=>h.textContent.includes(${JSON.stringify(text)})).scrollIntoView({behavior:'smooth',block:'start'})`;
run('org-club-edition', [
 {card:{kicker:'Cognition.X · Education OS · a reference design', title:'A Club is not a school <b>with different hours.</b>', sub:'Third Place: 225 drop-in-safe, mixed-age sessions in five strands, plus the Club Administrator Academy. Designed for the needs of Boys & Girls Clubs and organisations like them.', lines:['225 sessions','5 strands × 3 bands','144 administrator modules','no affiliation'], dur:10},
  say:"This platform has no affiliation with, endorsement from, or contact of any kind with Boys and Girls Clubs of America or any local Club. Nothing here uses their marks or programme names. What follows is an independent design, built from what is publicly known about how after-school youth development actually runs, offered for a Club to take, adapt or ignore."},
 {url:app('education-os','#/club'), settle:2600, chapter:'What a Club actually needs', caption:'Drop-in attendance · mixed ages · part-time staff · no authority over homework · two hours after a full school day.',
  say:"A Club is a third place, the one between home and school. There is no roster: a member may come on Tuesday and not on Thursday. There is no age grade: a nine-year-old and a fourteen-year-old share the table. The staff member running the session is often nineteen, part-time, three shifts in, with no prep time. Fourteen structural needs the school-day product gets wrong, and what this design does about each.",
  steps:[{drift:500, ms:2400},{eval:sec('club','What a Club actually needs'), dwell:2000},{drift:700, ms:5200},{cap:'The relationship is the product: every session is scored on whether it created contact between a member and an adult.', dwell:3000}]},
 {url:app('education-os','#/club'), settle:2600, chapter:'Seven goals, each measured honestly', caption:'Belong · Be counted on · Make something · Keep school survivable · Move and eat · Earn and understand money · Hand it on',
  say:"Seven goals, and how each is measured. Belong: every member known by name by two adults within a fortnight, measured by asking members, not by staff assertion. Be counted on: one real responsibility per term. Make something, finished and shown, never juried. Move and eat: no weights, no measurements, no body data of any kind, ever. Earn and understand money: every teen leaves with a real paid or costed experience. Hand it on.",
  steps:[{eval:sec('club','The seven goals'), dwell:1800},{drift:700, ms:5200}]},
 {url:app('education-os','#/club'), settle:2600, chapter:'The 3-2-1 card', caption:'Three minutes to start with no preparation, two things that must happen, one thing that must never.',
  say:"The whole programme is designed around one constraint: the person running the session had no preparation time. So every session ships a three-two-one card. Three minutes to start with no preparation. Two things that must happen. One thing that must never. Printed, laminated, on the wall. A staff member on their third shift can run any session from the card alone.",
  steps:[{eval:sec('club','The session shape'), dwell:1800},{drift:600, ms:4200}]},
 {url:app('education-os','#/club'), settle:2600, chapter:'The curriculum: 5 strands × 3 bands × 15 sessions', caption:'Money & Work · Teens 13–18. Every session: what happens, and what it never is.',
  say:"Five strands: homework and learning support, character and leadership, healthy lifestyles, money and work, voice, arts and story. Three bands: juniors, middles, teens. Fifteen sessions each, every one self-contained and order-independent. Here is money and work for teens: what happens in the session, and, in its own column, what it never is. Then any card, printed, ready for the wall.",
  steps:[{eval:sec('club','The curriculum'), dwell:1400},{click:'#v-club button:has-text("Money & Work")', dwell:1200},{click:'#v-club button:has-text("Teens · 13–18")', dwell:2400},{drift:600, ms:3600},{scroll:'#tp-card', dwell:900},{eval:"const s=document.getElementById('tp-card'); s.selectedIndex=Math.min(3, s.options.length-1); s.dispatchEvent(new Event('change',{bubbles:true}))", dwell:1200},{scroll:'#tp-out', dwell:3200}]},
 {url:app('education-os','#/club'), settle:2600, chapter:'The member ladder, ending in a real job', caption:'Member → Regular → Helper → Junior leader → Paid junior staff, on a real contract.',
  say:"The member ladder has five rungs and ends in a real job. Member: known by name. Regular: holds one small role that was actually needed. Helper: runs a piece of a session for the band below. Junior leader: plans and runs a whole session with an adult present but not leading. Paid junior staff: a real position with hours, pay, supervision and a reference. Paid at least the local minimum, on a real contract; anything else is not this rung.",
  steps:[{eval:sec('club','The member ladder'), dwell:1800},{drift:500, ms:3400},{eval:sec('club','What this programme refuses'), dwell:1800},{drift:500, ms:3200},{cap:'No body data. No photograph without written guardian consent. No teen used as unpaid staff. No behaviour scoring. No new reporting instrument.', dwell:3200}]},
 {url:app('education-os','#/clubadmin'), settle:2600, chapter:'The Club Administrator Academy', caption:'Nobody trains the administrator. Twelve tracks × three tiers × four modules, each ending in an instrument.',
  say:"And the second module: nobody trains the administrator. The sector promotes its best youth worker into a director's seat on a Friday and expects a building on Monday. Twelve tracks, three tiers, four modules each, about seventy-six hours, and every module ends in an instrument, not a takeaway. Safety and safeguarding first: open the building alone; the two-adult rule in a building with one adult; receive a disclosure without making it worse; know your own mandatory reporting law.",
  steps:[{drift:500, ms:2400},{eval:sec('clubadmin','The curriculum'), dwell:1800},{drift:600, ms:3800},{click:'#v-clubadmin button:has-text("Attendance, retention")', dwell:2600},{drift:400, ms:2400}]},
 {url:app('education-os','#/clubadmin'), settle:2600, chapter:'Ten instruments, and the first ninety days', caption:'The Monday board · the coverage grid · the drift read · the teen-cliff watch · the incident ladder · the funder pack',
  say:"Ten instruments a director keeps, each named with what it deliberately is not, because the failure mode of every administrator tool in this sector is that it quietly becomes surveillance of staff. The Monday board. The coverage grid. The drift read: members whose attendance changed, each with one named adult and one action, never a risk score attached to a child. Then the first ninety days in the seat: three weeks of learning before a single change.",
  steps:[{eval:sec('clubadmin','The ten instruments'), dwell:1800},{drift:600, ms:4200},{eval:sec('clubadmin','The first ninety days'), dwell:1800},{drift:600, ms:3600}]},
 {card:{kicker:'A reference design · zero deployments', title:'Built with partnerships in mind — <b>and none in hand.</b>', sub:'No certification, no claim of effectiveness, no affiliation with any named organisation. github.com/AGIFutureFoundation/Cognition.X', lines:['Education OS','v0.71.0','no affiliation claimed'], dur:9},
  say:"No Club has run this. No certification is offered, no effectiveness is claimed, and no partnership is implied. It is a reference design, published so that a Club can see exactly what would and would not exist before anybody agrees to anything. Cognition X. Open source, offline first."},
]).then(()=>console.log('DONE club')).catch(e=>{console.error(e);process.exit(1);});
