// Promo film — the Tenderloin pilot page in the Education OS: four layers authored
// from the Tenderloin Housing Clinic's published programmes and one pilot small
// enough to decline cheaply. No affiliation; the page's own refusals are spoken.
//   NODE_PATH=$(npm root -g) node tools/film/orgs/thc.js
const { run, app } = require('../film');
const sec = (view, text) => `[...document.querySelectorAll('#v-${view} h2')].find(h=>h.textContent.includes(${JSON.stringify(text)})).scrollIntoView({behavior:'smooth',block:'start'})`;
run('org-tenderloin-pilot', [
 {card:{kicker:'Cognition.X · Education OS · an unsolicited offer', title:'One building. One strand. <b>Twelve weeks.</b> Free.', sub:'Four mastery layers written from the Tenderloin Housing Clinic\'s five published programmes, and one pilot small enough to decline cheaply.', lines:['4 layers','1,000 blocks','12 sessions','no affiliation'], theme:'teal', dur:9},
  say:"The Tenderloin Housing Clinic is a real organisation in San Francisco with its own staff, its own lawyers and its own clients. It has not seen this, has not asked for it, and has no relationship with this platform. What follows was written from their five published programme descriptions, and is an unsolicited offer."},
 {url:app('education-os','#/thc'), settle:2600, chapter:'What their own site says', caption:'Over 3,000 clients a year · over 2,000 people housed · twenty-plus master-lease properties · five programmes.',
  say:"It starts from what their own site says. Over three thousand clients a year. Over two thousand people housed. More than twenty master-lease properties in the Mission, SOMA, the Tenderloin and Union Square. Five published programmes: permanent housing, recovery services, money management, legal assistance, community organizing.",
  steps:[{drift:500, ms:2400},{eval:sec('thc','What their own site says'), dwell:2600},{drift:300, ms:1800}]},
 {url:app('education-os','#/thc'), settle:2600, chapter:'Four layers, from four programmes', caption:'Housing & Tenancy · Money, Benefits & Entitlements · Reentry & Recovery Pathways · Neighbourhood, Safety & Civic Voice',
  say:"Four of those programmes became four mastery layers of two hundred and fifty blocks each. Permanent housing became Housing and Tenancy: what a lease says, habitability, eviction, moving. Money management became Money, Benefits and Entitlements, written for a budget with a payee and a benefits cliff in it. Recovery services became Reentry and Recovery Pathways. Community organizing became Neighbourhood, Safety and Civic Voice. Legal assistance became nothing, deliberately: T H C has lawyers, and this platform does not stand between a tenant and their attorney.",
  steps:[{eval:sec('thc','Four layers'), dwell:1800},{drift:700, ms:5200},{cap:'Legal Assistance → not a layer, deliberately. Taught as literacy, never as advice about a live case.', dwell:3000}]},
 {url:app('education-os','#/thc'), settle:2600, chapter:'Six refusals, specific to this population', caption:'No legal advice · no client record · no benefits determination · no clinical advice · nothing that can affect housing · no claim of partnership',
  say:"Six refusals, specific to this population. No legal advice, ever. No client record in this platform: no name, no case, no housing status. No benefits determination. No clinical or recovery advice. Nothing that can affect housing: no completion, score or attendance may reach a tenancy decision, and if a funder asks, the pilot ends rather than bending. And no claim of partnership until T H C signs something.",
  steps:[{eval:sec('thc','Six refusals'), dwell:1800},{drift:600, ms:5000}]},
 {url:app('education-os','#/thc'), settle:2600, chapter:'The pilot', caption:'8–15 adult tenants, voluntary · two THC staff · 90 minutes weekly, on site · printed packs · free.',
  say:"The pilot. One master-lease building, the Housing and Tenancy strand, twelve weeks. Eight to fifteen adult tenants, voluntary in the real sense: no housing consequence for joining, leaving, or never coming. Two T H C staff run it; this platform trains them and then is not in the room. Ninety minutes a week, on site, on paper, because a printed pack survives a room with no wifi and a person with no phone. What T H C provides: a room, two staff, and a decision about who is invited. What this platform provides: the materials, the training and the packs. Free.",
  steps:[{eval:sec('thc','The pilot'), dwell:1800},{drift:700, ms:6000},{cap:'What is measured: attendance, completion, and one anonymous question at week 12. What is not measured: anything about a person.', dwell:3200}]},
 {url:app('education-os','#/thc'), settle:2600, chapter:'Twelve sessions, already written', caption:'Week 1: what a room has to do. Week 8: a notice, and the clock it starts. Week 12: the transfer check.',
  say:"Twelve sessions, already written. What a room has to do. Heat, light and the hours they run. The document you signed and where it is. Rent: the amount, the date, the proof. Photographs that will still mean something in six months. A notice, and the clock it starts, with the same sentence every time: take it to the Law Office today. And week twelve: a crew explains their own building's repair problem to somebody who does not live there, well enough that the listener could act on it.",
  steps:[{eval:sec('thc','Twelve sessions'), dwell:1800},{drift:800, ms:6200}]},
 {url:app('education-os','#/thc'), settle:2600, chapter:'How to start, if it is worth starting', caption:'Today: read the refusals. This week: one conversation. If yes: print the packs. Week twelve: write down what happened.',
  say:"How to start, if it is worth starting. Today, read the page and the refusals; if anything misdescribes how T H C works, it is wrong and should be corrected first. This week, one conversation with an organiser and a case manager. If yes, print the twelve packs: no licence, no account, no procurement. Two hours of staff training. Then start, with eight people, in one building, on paper. At week twelve, write down what happened, including if it did not help. That report is T H C's.",
  steps:[{eval:sec('thc','How to start'), dwell:1800},{drift:600, ms:5200}]},
 {card:{kicker:'An offer, not a partnership', title:'Small enough to be <b>declined cheaply.</b>', sub:'No data, no integration, no contract, and nothing that touches anybody\'s housing. github.com/AGIFutureFoundation/Cognition.X', lines:['Community Edition','free','no affiliation claimed'], theme:'teal', dur:9},
  say:"The most likely honest outcome is that T H C reads this and declines, and that would be a reasonable decision by people who know their clients and do not know us. What is offered is deliberately small enough to be declined cheaply. Cognition X. Open source, offline first."},
]).then(()=>console.log('DONE thc')).catch(e=>{console.error(e);process.exit(1);});
