// Promo film — the Willie L. Brown Jr. Institute Track model in the Education OS.
// Recorded from the real app; the disclaimer the app carries is spoken and shown.
//   NODE_PATH=$(npm root -g) node tools/film/orgs/wlb.js
const { run, app } = require('../film');
const sec = (view, text) => `[...document.querySelectorAll('#v-${view} h2')].find(h=>h.textContent.includes(${JSON.stringify(text)})).scrollIntoView({behavior:'smooth',block:'start'})`;
run('org-wlb-institute-track', [
 {card:{kicker:'Cognition.X · Education OS · a proposal', title:'A legacy <b>taught</b>, not remembered.', sub:'The Willie L. Brown Jr. Institute Track model: twelve published principles turned into a K–12 civic-leadership cornerstone for every state edition.', lines:['33 strands','3,333 courses','33,333 modules','11 bridges'], theme:'gold', dur:9},
  say:"This is a proposal, built from the public mission of the Willie L. Brown Junior Institute of Politics and Public Service and its Fellowship at San Francisco State. It is not affiliated with, endorsed by, or reviewed by the Institute, S F State, or Mayor Brown. What follows is what a partnership could look like."},
 {url:app('education-os','#/wlb'), settle:2600, chapter:'The cornerstone', caption:'"Public service is the most noble of professions." — the Institute\'s own vision statement, on the page.',
  say:"The track opens with the Institute's own words. Public service is the most noble of professions. From that vision: thirty-three strands, three thousand three hundred and thirty-three courses, and thirty-three thousand modules, from kindergarten to a twelfth-grader's Fellowship application. Every course cites the principle it serves.",
  steps:[{scroll:'#wlb-top', dwell:1500},{drift:500, ms:2600},{cap:'3,333 courses · 33,333 modules · 33 strands · 13 grades · 11 bridges', dwell:2200}]},
 {url:app('education-os','#/wlb'), settle:2600, chapter:'Twelve principles, with their sources', caption:'Each principle names its source and the strands that carry it.',
  say:"Twelve principles, each drawn from the Institute's statements, the Fellowship's design, alumni testimony and Mayor Brown's own words, each with its source on the page. Recruit and include students of every background. Hands-on learning inside real public agencies, with a cohort, a seminar and a stipend. Take on the cases others dismiss as hopeless. Bringing everyone along with you.",
  steps:[{eval:sec('wlb','What he has focused on teaching'), dwell:1600},{drift:700, ms:4200},{cap:'Principle 3: a junior placement at every grade band and a weekly seminar circle from grade 3.', dwell:2400},{drift:600, ms:3000}]},
 {url:app('education-os','#/wlb'), settle:2600, chapter:'Thirty-three strands in five families', caption:'Service & governance · Rights & justice · Economy & place · Health & wellbeing · Equity & the person',
  say:"Thirty-three strands in five families. Service and governance. Rights and justice: civil rights and the law, juvenile justice and second chances, housing justice, affirmative action and breaking ceilings. Economy and place. Health and wellbeing. Equity and the person, where the first-generation strand and the Mineola-to-City stories live. Ninety-one courses in each strand, kindergarten to twelfth grade.",
  steps:[{eval:sec('wlb','Thirty-three strands'), dwell:1400},{click:'#wlb-fam button:has-text("Rights & justice")', dwell:2600},{drift:400, ms:2200},{click:'#wlb-fam button:has-text("Equity & the person")', dwell:2600},{drift:300, ms:1800}]},
 {url:app('education-os','#/wlb'), settle:2600, chapter:'Eleven bridges', caption:'Junior Fellowship · Seminar Circles · Family Civic Nights · Fellowship On-Ramp · Civic Seal Portfolio · Mineola-to-City Stories',
  say:"Eleven bridges carry the track out of the classroom. A junior fellowship at every grade band. The Friday seminar circle from grade three. Family civic nights in twenty-one languages. The fellowship on-ramp in grades eleven and twelve, mapped to the Institute's own programme. A civic seal portfolio toward the State Seal of Civic Engagement. And the Mineola-to-City stories: oral histories of barrier-crossing, the founder's and each family's own.",
  steps:[{eval:sec('wlb','Eleven bridges'), dwell:1600},{drift:700, ms:4600},{cap:'Each bridge: two courses per grade K–12 plus family, summer, educator and community editions.', dwell:2400}]},
 {url:app('education-os','#/wlb'), settle:2600, chapter:'Courses by grade', caption:'Grade 8, California: 253 courses, standards cited, one line per strand.',
  say:"Pick a grade. Eighth grade in California: two hundred and fifty-three courses, the standards they cite, and one line per strand: following one public decision from meeting to street; the mock legislature with committees, amendments and votes; public budgets in real numbers; the affordable-housing design challenge.",
  steps:[{eval:sec('wlb','Courses by grade'), dwell:1200},{click:'#wlb-tabs button:has-text("Gr 8")', dwell:2400},{drift:600, ms:3600},{click:'#wlb-tabs button:has-text("Gr 12")', dwell:2000},{drift:500, ms:2600}]},
 {url:app('education-os','#/wlb'), settle:2600, chapter:'Every state edition', caption:'The same track, localised: its capital, its legislature, its standards, its civic seal.',
  say:"The California cornerstone is the origin, and every state edition localises it: the capital and the legislature, the local unit, the standards, the civic seal, the placement ladder. Fifty-six editions. The track exports as one file, and the partnership is proposed, not claimed.",
  steps:[{scroll:'#wlb-top', dwell:1000},{select:'#wlb-st', value:'LA', dwell:2600},{drift:400, ms:2000},{select:'#wlb-st', value:'TX', dwell:2200},{scroll:'#wlb-exp', dwell:900},{click:'#wlb-exp', dwell:2200}]},
 {card:{kicker:'A proposal · not an affiliation', title:'Offered under a partnership agreement and <b>the Institute\'s review</b> of every course.', sub:'Open source, offline-first, nothing leaves the page on its own. github.com/AGIFutureFoundation/Cognition.X', lines:['Education OS','v0.71.0','no affiliation claimed'], dur:9},
  say:"A named track would be offered under a partnership agreement and the Institute's review of every course. Cognition X. Open source, offline first. Nothing leaves the page on its own."},
]).then(()=>console.log('DONE wlb')).catch(e=>{console.error(e);process.exit(1);});
