const { run, app } = require('./film');
run('social-5-leadership-as-craft', [
 {card:{kicker:'Cognition.X · the Legacy Institute', title:'Leadership, <b>taught as craft.</b>', sub:'Built on the public record and published principles of the Willie L. Brown Jr. Institute of Politics and Public Service.', lines:['12 principles','5 strands × 5 eras','125 courses'], theme:'gold'},
  say:"The civic cornerstone of Cognition X: the Legacy Institute. Leadership, ethics and civic duty, taught as craft."},
 {url:app('louisiana','#/institute'), chapter:'Twelve principles', caption:'Each principle with its source — and how it is taught.',
  say:"Twelve principles, built on the public record and published principles of the Willie L. Brown Junior Institute of Politics and Public Service. Each one with its source, and how it is taught.",
  steps:[{scroll:'#arcs', dwell:1400},{drift:700, ms:2600}]},
 {url:app('louisiana','#/institute'), chapter:'The record', caption:'Four decades of public life, read as curriculum.',
  say:"Four decades of public life, read as curriculum.",
  steps:[{scroll:'#recordgrid', dwell:1800}]},
 {url:app('louisiana','#/institute'), chapter:'The Leadership Ladder', caption:'Five strands · five eras · 125 courses · a ten-module method · a graduation seal.',
  say:"The Leadership Ladder: five strands across five eras, one hundred twenty-five courses, a ten-module method, bridge projects at grades five and eight, and a graduation seal. For educators, this is the training track.",
  steps:[{scroll:'#strandpick', dwell:900},{select:'#strandpick', value:{index:1}, dwell:1200},{scroll:'#laddertable', dwell:1600},{select:'#strandpick', value:{index:3}, dwell:1600}]},
 {url:app('louisiana','#/institute'), chapter:'The Fellowship pattern', caption:'Paid public-agency placements for students who faced barriers.',
  say:"At the top of the ladder, the Fellowship pattern: paid placements in public agencies for students who faced barriers to higher education.",
  steps:[{scroll:'#wlbfellow', dwell:2400}]},
 {url:app('states','#'), chapter:'Any state, any country', caption:'One template localizes the Institute Model to every capital.',
  say:"One template localizes the Institute Model to every state capital — and to any country.",
  steps:[{click:'.tab[data-r="institute"]', dwell:1400},{drift:500, ms:2000}]},
 {url:app('louisiana','#/institute'), chapter:'The disclaimer', caption:'A proposal from the public record — not affiliated, not endorsed.',
  say:"A proposal built from the Institute's public mission — not affiliated, not endorsed, not reviewed by the Institute. A named track would come under a partnership agreement and the Institute's review of every course.",
  steps:[{scroll:'#wlbdisc', dwell:2600}]},
 {card:{kicker:'Cognition.X', title:'Civic duty, <b>as craft.</b>', sub:'github.com/AGIFutureFoundation/Cognition.X', lines:['open source','localizable anywhere'], theme:'gold'},
  say:"Civic duty, as craft. Cognition X."},
]).then(()=>console.log('DONE 5')).catch(e=>{console.error(e);process.exit(1);});
