#!/usr/bin/env python3
"""Build the Education OS app from its template + the canonical dataset.

Roadmap Phase 2: apps/education-os/index.html is now a BUILD PRODUCT.
The base is apps/education-os/template.html (the last hand-grown "gov"
build, kept verbatim as the app shell and legacy content). This tool
appends a canonical overlay <script> that, after all the app's own
rounds have run, replaces DATA.sectorBlocks with the sector master-block
library as it stands in data/blocks.csv — so edits to the dataset flow
into the app, and the app's sector library has exactly one source of
truth.

Field fidelity: the app renders each row's task and outcome separately;
blocks.csv stores them joined in transfer_check. The extraction sidecar
data/generated/app-master-blocks.map.json preserves the original
boundary per code. When a dataset row's check still equals the joined
original, the overlay re-emits the original [task, outcome]; when the
dataset row was edited, the edited check ships as the task with the
outcome left empty — the dataset wins.

Output stays a single offline file, per the app's standing constraint.
Deterministic: same inputs -> same output.
"""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "apps" / "education-os" / "template.html"
OUT = ROOT / "apps" / "education-os" / "index.html"
MAP = ROOT / "data" / "generated" / "app-master-blocks.map.json"

PACK_SECTOR = {
    "Cognition.X : Corporate OS": "corp",
    "Cognition.X : Science OS": "sci",
    "Cognition.X : Robotics OS": "rob",
    "Cognition.X : Global Health OS": "gh",
    "Cognition.X : Multilateral OS": "mlt",
    "Cognition.X : Sapient OS": "sap",
    "Cognition.X : Education OS": "edu",
    "Non-Profit Practice": "npo",
}


def main():
    version = (ROOT / "VERSION").read_text().strip()
    parts = json.loads(MAP.read_text(encoding="utf-8"))
    rows = [r for r in csv.DictReader(open(ROOT / "data" / "blocks.csv", newline="", encoding="utf-8"))
            if r["code"].startswith("T0") and r["pack"] in PACK_SECTOR]
    out = []
    kept = edited = 0
    for r in sorted(rows, key=lambda x: (x["pack"], x["code"])):
        orig = parts.get(r["code"])
        joined = (orig[0].rstrip(".") + ". " + orig[1]).strip() if orig else None
        if orig and r["transfer_check"] == joined:
            task, outcome = orig
            kept += 1
        else:
            task, outcome = r["transfer_check"], ""
            edited += 1
        out.append([PACK_SECTOR[r["pack"]], r["credential"], r["code"],
                    r["theme"], task, outcome])
    payload = json.dumps(out, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    overlay = (
        "\n<script>/* CX canonical overlay v" + version + " — generated by "
        "tools/build_education_os.py; DATA.sectorBlocks now sourced from "
        "data/blocks.csv. Do not edit: rebuild instead. */\n"
        ";(function(){try{\n"
        " if (typeof DATA !== 'undefined'){\n"
        "  DATA.sectorBlocks = " + payload + ";\n"
        "  DATA.cxCanonical = {version:'" + version + "', sectorBlocks: DATA.sectorBlocks.length,"
        " source:'data/blocks.csv'};\n"
        " }\n"
        "}catch(e){}})();\n</script>\n"
    )
    html = TEMPLATE.read_text(encoding="utf-8", errors="replace") + overlay
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(html)/1e6:.2f} MB — "
          f"{len(out)} canonical sector blocks injected ({kept} with original "
          f"task/outcome fields, {edited} dataset-edited)")


if __name__ == "__main__":
    main()
