#!/usr/bin/env python3
"""Turn a cohort's collected cx-evidence/1 files into the curriculum review
board's packet — Markdown on stdout (or --out FILE).

Extends tools/evidence_triage.py (whose merge and thresholds it reuses)
into the packet the board reads at a sitting (docs/BOARD_PACKET.md):

  1. the cohort summary — files, sites, learner-touches, checks, witnessed
     outcomes and the overall not-yet rate;
  2. every track with activity, with its witnessed rate and the rubric
     the assessors read (data/rubrics/) where one exists;
  3. revision priorities (the triage thresholds) and unreported tracks;
  4. the standing-queue status of the packs the cohort used — machine-
     authored packs not yet reviewed are named so the board can order them;
  5. the v1.0 gate status that evidence alone can establish: a full track
     with witnessed checks reported by at least one site. The rest of the
     gate — an unmodified release, a credential issued, keys exchanged, the
     board's own review — is the board's record and is printed as a form.

Usage:
    python3 tools/cohort_report.py [evidence.json ...] [--out packet.md]
    (no files: reads data/evidence/*.json — the synthetic sample)

Evidence proposes; the board disposes. The packet never edits anything.
"""

import csv
import json
import sys
from collections import Counter
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from evidence_triage import load, dataset_tracks, MIN_WITNESSED, NOTYET_FLAG  # noqa: E402


def machine_authored():
    src = {r["pack"] for r in csv.DictReader(open(ROOT / "data" / "source" / "Cognition.X_all_blocks.csv", newline="", encoding="utf-8"))}
    packs = json.loads((ROOT / "data" / "manifest.json").read_text(encoding="utf-8"))["packs"]
    return {p["name"]: p for p in packs if p["name"] not in src}


def rubrics():
    out = {}
    for p in sorted((ROOT / "data" / "rubrics").glob("*.json")):
        d = json.loads(p.read_text(encoding="utf-8"))
        packs = {p_["slug"]: p_["name"] for p_ in json.loads((ROOT / "data" / "manifest.json").read_text(encoding="utf-8"))["packs"]}
        for r in d["rubrics"]:
            out[(packs.get(r["pack"], r["pack"]), r["track"])] = r
    return out


def build(paths):
    merged, files = load(paths)
    if not merged:
        raise SystemExit("no usable cx-evidence/1 files")
    sites = set()
    for path in paths:
        d = json.loads(Path(path).read_text(encoding="utf-8"))
        if d.get("format") == "cx-evidence/1":
            sites.add(d.get("site") or "(unlabelled site)")
    tot = Counter()
    rows = []
    for (pack, track), a in merged.items():
        w = a["witnessedConfirmed"] + a["witnessedNotYet"]
        rate = a["witnessedNotYet"] / w if w else 0.0
        rows.append({"pack": pack, "track": track, **a, "witnessed": w, "rate": rate})
        for k in ("checksRecorded", "witnessedConfirmed", "witnessedNotYet", "learners"):
            tot[k] += a[k]
    rows.sort(key=lambda r: (-r["checksRecorded"], r["track"]))
    prio = sorted([r for r in rows if r["witnessed"] >= MIN_WITNESSED and r["rate"] >= NOTYET_FLAG], key=lambda r: -r["rate"])
    universe = dataset_tracks()
    unreported = sorted(universe - set(merged)) if universe else []
    mach = machine_authored()
    rub = rubrics()
    used_packs = sorted({r["pack"] for r in rows})
    tw = tot["witnessedConfirmed"] + tot["witnessedNotYet"]
    full = [r for r in rows if r["witnessedConfirmed"] >= 50]
    version = (ROOT / "VERSION").read_text().strip()

    L = [f"# Cohort packet for the Curriculum Review Board", "",
         f"> Generated by `tools/cohort_report.py` on {date.today().isoformat()} from {files} opt-in, aggregate `cx-evidence/1` file(s) — per-track counts only, no names, no per-learner rows, sent by a person. Dataset version {version}. Evidence proposes; the board disposes.", "",
         "## 1. The cohort at a glance", "",
         "| Files | Sites | Tracks with activity | Learner-touches | Checks recorded | Witnessed confirmed | Witnessed not-yet | Not-yet rate |", "|---:|---:|---:|---:|---:|---:|---:|---:|",
         f"| {files} | {len(sites)} | {len(rows)} | {tot['learners']} | {tot['checksRecorded']} | {tot['witnessedConfirmed']} | {tot['witnessedNotYet']} | {(tot['witnessedNotYet']/tw if tw else 0):.0%} |", "",
         "Sites: " + "; ".join(sorted(sites)) + ".", "",
         "## 2. Every track with activity", "",
         "| Track | Pack | Checks | Witnessed ✓ | Witnessed ↺ | Not-yet rate | Learners | Rubric |", "|---|---|---:|---:|---:|---:|---:|---|"]
    for r in rows:
        rb = rub.get((r["pack"], r["track"]))
        L.append(f"| {r['track']} | {r['pack']} | {r['checksRecorded']} | {r['witnessedConfirmed']} | {r['witnessedNotYet']} | {r['rate']:.0%} | {r['learners']} | {'yes — ' + rb['note'][:80] + ('…' if len(rb['note']) > 80 else '') if rb else 'none yet'} |")
    L += ["", f"## 3. Revision priorities (not-yet rate ≥ {NOTYET_FLAG:.0%} over ≥ {MIN_WITNESSED} witnessed attempts)", ""]
    if prio:
        for r in prio:
            L.append(f"- **{r['track']}** [{r['pack']}] — {r['witnessedNotYet']} not-yet of {r['witnessed']} witnessed across {r['sites']} site(s). The check may be mis-pitched for its band, or the theme under-taught. Propose a supersession or a teaching note; never edit an id.")
    else:
        L.append("None flagged at the current thresholds.")
    L += ["", f"## 4. Unreported tracks ({len(unreported)} of {len(universe)})", "",
          "No submitting site reported activity on these. That is not the same as unused: review for relevance or reachability, and ask whether the sites that use them simply have not sent evidence.", ""]
    for pack, track in unreported[:12]:
        L.append(f"- {track} [{pack}]")
    if len(unreported) > 12:
        L.append(f"- …and {len(unreported) - 12} more.")
    L += ["", "## 5. Standing-queue status of the packs this cohort used", "",
          "| Pack | Origin | Board status | Action |", "|---|---|---|---|"]
    for p in used_packs:
        if p in mach:
            L.append(f"| {p} | generated from a spec ({mach[p]['blocks']:,} blocks) | **not yet reviewed** — standing queue | schedule before or at this sitting; the cohort has used it |")
        else:
            L.append(f"| {p} | imported source content | reviewed as source on request | — |")
    L += ["", "## 6. The v1.0 gate — what this evidence establishes", "",
          "| Condition | From this evidence | Board's record |", "|---|---|---|",
          "| A named external cohort ran a full track with witnessed checks | " + ("**yes** — " + ", ".join("%s (%d witnessed)" % (r["track"], r["witnessedConfirmed"]) for r in full) if full else "not yet — no track shows 50 witnessed confirmations") + " | Cohort name: ____________ |",
          "| On an unmodified release | cannot be read from evidence | Checksums verified on: ________ (`sha256sum -c apps/CHECKSUMS.sha256`) |",
          "| At least one learner holds a signed credential | cannot be read from evidence (records are not exported to the board) | Record id: ____________ verified with `tools/verify_record.js` on ________ |",
          "| Records-office keys exchanged with another office | cannot be read from evidence | Offices: ____________ ⇄ ____________ on ________ |",
          "| This board has reviewed the packs the cohort used | see section 5 | Packs approved: ____________ at sitting ________ |",
          "", "When every row carries a date, v1.0 is cut (`docs/ROADMAP.md`, *The path to v1.0*)."]
    return "\n".join(L) + "\n"


def main():
    args = sys.argv[1:]
    out = None
    if "--out" in args:
        i = args.index("--out"); out = Path(args[i + 1]); del args[i:i + 2]
    paths = [Path(a) for a in args] or sorted((ROOT / "data" / "evidence").glob("*.json"))
    if not paths:
        raise SystemExit("no evidence files given and none under data/evidence/")
    text = build(paths)
    if out:
        out.write_text(text, encoding="utf-8"); print(f"wrote {out}")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
