#!/usr/bin/env python3
"""Regenerate docs/STATE_COMPLIANCE.md from data/states/compliance.json.

One table of all fifty states — homeschool tier, privacy law tier, charity
registration, apprenticeship agency, sales-tax exemption, the foreign
nonprofit qualification fee and the estimated one-time / annual compliance
cost — under the layer's own disclaimer. CI regenerates it and fails on
drift, so the document can never disagree with the data.

    python3 tools/compliance_report.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "states" / "compliance.json"
OUT = ROOT / "docs" / "STATE_COMPLIANCE.md"


def money(v):
    return "—" if v is None else f"${v:,.0f}" if float(v).is_integer() else f"${v:,.2f}"


def fee(f):
    return money(f["amount"]) if f.get("amount") is not None else (f.get("band") or "—")


def main():
    c = json.loads(SRC.read_text(encoding="utf-8"))
    ss = c["states"]
    reg = sum(1 for s in ss if s["charity"]["required"])
    op = sum(1 for s in ss if s["privacy"]["tier"] == "operator-law")
    saa = sum(1 for s in ss if s["apprenticeship"]["type"] == "SAA")
    tiers = {t: sum(1 for s in ss if s["homeschool"]["tier"] == t) for t in ("none", "low", "moderate", "high")}
    lo = min(s["cost"]["one_time"]["low"] for s in ss); hi = max(s["cost"]["one_time"]["high"] for s in ss)
    fixed = sum(1 for s in ss if s.get("breach", {}).get("deadline_days"))
    lines = [
        "# State compliance — the fifty-state layer",
        "",
        "> **Not legal advice.** Every figure below is flagged *verify* in the data: fees, forms and",
        f"> thresholds change yearly and are recorded as of **{c['asOf']}**. Confirm each with the named",
        "> agency (or counsel) before filing. Nothing here asserts that Cognition.X is approved,",
        "> registered or listed anywhere.",
        "",
        "Generated by `tools/compliance_report.py` from",
        "[`data/states/compliance.json`](../data/states/compliance.json) — the source the States app's",
        "*Compliance* view and the Louisiana State Admin dashboard render. Regenerated and drift-checked",
        "in CI on every push.",
        "",
        "## What the layer covers",
        "",
        "| Domain | What it is |",
        "|---|---|",
    ]
    lines += [f"| {d['name']} | {d['what']} |" for d in c["domains"]]
    lines += [
        "",
        "## At a glance",
        "",
        f"- **{reg}** states require charitable-solicitation registration before soliciting residents; **{50-reg}** do not (or only with paid solicitors).",
        f"- **{op}** states have a SOPIPA-style statute binding ed-tech operators; the rest run on FERPA, COPPA and district policy.",
        f"- **{saa}** states register apprenticeship programs through a State Apprenticeship Agency; **{50-saa}** through the federal Office of Apprenticeship.",
        f"- Homeschool regulation: **{tiers['none']}** no-notice · **{tiers['low']}** low · **{tiers['moderate']}** moderate · **{tiers['high']}** high.",
        f"- Breach notification: **{fixed}** states set a fixed outer deadline after discovery (30–60 days); **{50-fixed}** say 'without unreasonable delay'. Regulator-notice thresholds vary; verify with the attorney general.",
        f"- Estimated one-time compliance cost per state: **{money(lo)}–{money(hi)}** under the stated assumptions (one program office, ten background checks; excludes staff time, counsel, insurance and devices).",
        "",
        "## The fifty states",
        "",
        "| State | Homeschool | Privacy | Charity reg. | Apprenticeship | Sales-tax exemption | Breach deadline | Foreign nonprofit fee | One-time est. | Annual est. |",
        "|---|---|---|---|---|---|---|---:|---:|---:|",
    ]
    for s in sorted(ss, key=lambda x: x["name"]):
        stx = "no state tax" if not s["sales_tax"]["state_sales_tax"] else ("available" if s["sales_tax"]["nonprofit_exemption"] else "none")
        lines.append(f"| {s['name']} | {s['homeschool']['tier']} | {'operator law' if s['privacy']['tier']=='operator-law' else 'baseline'} | "
                     f"{'required' if s['charity']['required'] else 'no'} | {s['apprenticeship']['type']} | {stx} | {(str(s['breach']['deadline_days'])+' days') if s.get('breach',{}).get('deadline_days') else 'no fixed count'} | {fee(s['nonprofit']['fee'])} | "
                     f"{money(s['cost']['one_time']['low'])}–{money(s['cost']['one_time']['high'])} | {money(s['cost']['annual']['low'])}–{money(s['cost']['annual']['high'])} |")
    lines += [
        "",
        "## The national baseline",
        "",
    ]
    N = c["national"]
    lines += [f"- {x}" for x in N["privacy"]["federal"]]
    lines += ["", f"**What the platform's architecture changes.** {N['privacy']['platform']}", "",
              f"**Accessibility.** {N['accessibility']['note']} {N['accessibility']['platform']}", "",
              f"**Background checks.** {N['background']['note']}", "",
              f"**Mandated reporting.** {N['mandated']['note']}", "",
              f"**Nonprofit registration.** {N['nonprofit']['note']}", "",
              f"**Charitable solicitation.** {N['charity']['note']} {N['charity']['instrument']}", "",
              f"**Apprenticeship.** {N['apprenticeship']['note']} ({N['apprenticeship']['federal']})", "",
              f"**CTE credential lists.** {N['cte']['note']}", "",
              f"**Sales tax.** {N['sales_tax']['note']}", "",
              f"**Breach notification and cybersecurity.** {N['breach']['note']} {N['breach']['platform']}", "",
              "## Maintaining the layer", "",
              "Each state entry carries `sources` (the agencies to confirm with) and every fee carries `asOf` and `verify`.",
              "A correction is a PATCH release: edit the JSON, run this script, and the tests will hold the shape.",
              "The per-state checklist exports from the States app as `cxstate-compliance/1` JSON and prints.", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(ss)} states")


if __name__ == "__main__":
    main()
