#!/usr/bin/env python3
"""Generate docs/CONTROL_REGISTER.md from data/policy/controls.json and
check every control's evidence resolves: a test name that exists in
tests/test_platform.py, a smoke check in tests/browser/smoke.js, a CI step
in .github/workflows/validate.yml, or a document or file in the tree.

Exit 1 if any evidence reference is dangling — a control may be open, but
it may not point at proof that is not there. Regenerated and drift-checked
in CI.
"""

import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "policy" / "controls.json"
OUT = ROOT / "docs" / "CONTROL_REGISTER.md"


def evidence_ok(ev):
    t, ref = ev["type"], ev["ref"]
    if t == "test":
        return re.search(rf"^def {re.escape(ref)}\(", (ROOT / "tests" / "test_platform.py").read_text(encoding="utf-8"), re.M) is not None
    if t == "smoke":
        return f"async function {ref}(" in (ROOT / "tests" / "browser" / "smoke.js").read_text(encoding="utf-8")
    if t == "ci":
        return f"- name: {ref}" in (ROOT / ".github" / "workflows" / "validate.yml").read_text(encoding="utf-8")
    if t in ("doc", "file"):
        return ref == "docs/CONTROL_REGISTER.md" or (ROOT / ref).exists()
    return False


def validate(doc):
    errs = []
    if doc.get("format") != "cx-controls/1":
        errs.append("format must be cx-controls/1")
    if "NOT LEGAL ADVICE" not in doc.get("note", ""):
        errs.append("note must say NOT LEGAL ADVICE")
    ids = Counter(c["id"] for c in doc["controls"])
    for k, n in ids.items():
        if n > 1:
            errs.append(f"duplicate control id {k}")
    for c in doc["controls"]:
        for k in ("id", "level", "domain", "title", "requirement", "source", "owner", "status", "evidence", "wave", "next"):
            if k not in c or c[k] in ("", None, []):
                errs.append(f"{c.get('id','?')}: missing {k}")
        if c.get("level") not in doc["levels"]:
            errs.append(f"{c['id']}: unknown level {c.get('level')!r}")
        if c.get("status") not in doc["statuses"]:
            errs.append(f"{c['id']}: unknown status {c.get('status')!r}")
        if c.get("owner") not in ("software", "adopter", "both"):
            errs.append(f"{c['id']}: owner must be software, adopter or both")
        for ev in c.get("evidence", []):
            if not evidence_ok(ev):
                errs.append(f"{c['id']}: evidence {ev['type']} {ev['ref']!r} does not resolve")
    return errs


def main():
    doc = json.loads(SRC.read_text(encoding="utf-8"))
    errs = validate(doc)
    if errs:
        for e in errs:
            print("✗", e)
        sys.exit(1)
    cs = doc["controls"]
    by_status = Counter(c["status"] for c in cs)
    by_level = Counter(c["level"] for c in cs)
    version = (ROOT / "VERSION").read_text().strip()
    L = ["# Security and compliance control register", "",
         f"> **Not legal advice.** Generated by `tools/controls_report.py` from [`data/policy/controls.json`](../data/policy/controls.json) at v{version}; every evidence reference is checked to exist in CI. Sources are cited as commonly published — verify with the agency or counsel. The roadmap that orders the open items is [`COMPLIANCE_ROADMAP.md`](COMPLIANCE_ROADMAP.md).", "",
         f"**{len(cs)} controls** · met {by_status['met']} · partial {by_status['partial']} · open {by_status['open']}", "",
         "| Level | Controls | Met | Partial | Open |", "|---|---:|---:|---:|---:|"]
    for lv, desc in doc["levels"].items():
        sub = [c for c in cs if c["level"] == lv]
        st = Counter(c["status"] for c in sub)
        L.append(f"| **{lv}** — {desc} | {len(sub)} | {st['met']} | {st['partial']} | {st['open']} |")
    L += ["", "Status words: " + "; ".join(f"**{k}** — {v}" for k, v in doc["statuses"].items()) + ".", ""]
    def evtxt(ev):
        t, r = ev["type"], ev["ref"]
        if t == "test": return f"test `{r}`"
        if t == "smoke": return f"browser `{r}`"
        if t == "ci": return f"CI step *{r}*"
        return f"[`{r}`](../{r})"
    for lv, desc in doc["levels"].items():
        sub = [c for c in cs if c["level"] == lv]
        if not sub:
            continue
        L += [f"## {lv.capitalize()} — {desc}", "",
              "| Id | Control | Requirement · source | Owner | Status | Evidence | Wave | Next |",
              "|---|---|---|---|---|---|---:|---|"]
        for c in sub:
            L.append(f"| {c['id']} | **{c['title']}** | {c['requirement']} *({c['source']})* | {c['owner']} | {c['status']} | {'; '.join(evtxt(e) for e in c['evidence'])} | {c['wave']} | {c['next']} |")
        L.append("")
    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(cs)} controls · met {by_status['met']} · partial {by_status['partial']} · open {by_status['open']}")


if __name__ == "__main__":
    main()
