#!/usr/bin/env python3
"""Generate the data-quality dashboard (docs/DATA_QUALITY.md).

The roadmap's Phase 1 "data quality dashboard generated in CI": a
per-pack completeness table computed from the canonical dataset, so
content debt is visible on every push instead of remembered. CI
regenerates this file and fails if it drifts from the committed copy —
the same pattern as the dataset and the apps.

Measured per pack (and totalled):
  blocks · tracks · % rows with a description · % descriptions that are
  band-suffix duplicates ("— at <band>", the known content debt) ·
  % rows with code+level · shortest transfer check (a lint canary).

Deterministic: same dataset, same file.
"""

import csv
import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "DATA_QUALITY.md"

SUFFIX = re.compile(r"— at .{1,20}$")  # "— at K–2" style band suffixes


def main():
    rows = list(csv.DictReader(open(ROOT / "data" / "blocks.csv",
                                    newline="", encoding="utf-8")))
    packs = OrderedDict()
    for r in rows:
        packs.setdefault(r["pack"], []).append(r)

    lines = [
        "# Data Quality Dashboard",
        "",
        "Generated by `tools/data_quality.py` from `data/blocks.csv` — never",
        "hand-edited. CI regenerates it on every push and fails on drift, so",
        "this table is always current with the dataset.",
        "",
        f"**{len(rows):,} blocks · {len(packs)} packs · "
        f"{len({(r['pack'], r['track']) for r in rows if r['track']})} tracks · "
        f"{len({r['credential'] for r in rows})} credentials**",
        "",
        "The known content debt (see the roadmap): band-suffix descriptions",
        "share one sentence across bands with an “— at ‹band›” suffix; the",
        "irregular foundation rows carry structural `code`/`level` but await",
        "authored descriptions. Neither is hidden — both are counted here.",
        "",
        "| Pack | Blocks | Tracks | Desc % | Band-suffix % | Code+level % | Min check len |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, pr in packs.items():
        n = len(pr)
        tracks = len({r["track"] for r in pr if r["track"]})
        desc = sum(1 for r in pr if r["description"].strip())
        suff = sum(1 for r in pr if SUFFIX.search(r["description"].strip()))
        cl = sum(1 for r in pr if r["code"].strip() and r["level"].strip())
        minchk = min(len(r["transfer_check"]) for r in pr)
        lines.append(
            f"| {name} | {n} | {tracks} | {100*desc//n}% | {100*suff//n}% "
            f"| {100*cl//n}% | {minchk} |")

    desc_all = sum(1 for r in rows if r["description"].strip())
    suff_all = sum(1 for r in rows if SUFFIX.search(r["description"].strip()))
    cl_all = sum(1 for r in rows if r["code"].strip() and r["level"].strip())
    lines += [
        "",
        f"**Dataset-wide:** descriptions {100*desc_all//len(rows)}% · "
        f"band-suffix {100*suff_all//len(rows)}% · code+level "
        f"{100*cl_all//len(rows)}% · shortest transfer check "
        f"{min(len(r['transfer_check']) for r in rows)} chars.",
        "",
    ]
    text = "\n".join(lines)
    changed = (not OUT.exists()) or OUT.read_text(encoding="utf-8") != text
    OUT.write_text(text, encoding="utf-8")
    print(f"{'wrote' if changed else 'unchanged'} {OUT.relative_to(ROOT)} "
          f"({len(packs)} packs)")


if __name__ == "__main__":
    main()
