#!/usr/bin/env python3
"""Generate the data-quality dashboard (docs/DATA_QUALITY.md).

The roadmap's Phase 1 "data quality dashboard generated in CI": a
per-pack completeness table computed from the canonical dataset, so
content debt is visible on every push instead of remembered. CI
regenerates this file and fails if it drifts from the committed copy —
the same pattern as the dataset and the apps.

Measured per pack (and totalled):
  blocks · tracks · % rows with a description · % descriptions that are
  band-suffix duplicates ("— at <band>", the known content debt) ·
  % rows with code+level · shortest transfer check (a lint canary).

Deterministic: same dataset, same file.
"""

import csv
import json
import sys
import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "DATA_QUALITY.md"

SUFFIX = re.compile(r"— at .{1,20}$")  # "— at K–2" style band suffixes
LEVEL_WORDS = {"Explorer", "Builder", "Practitioner", "Lead"}  # not credential names


def main():
    rows = list(csv.DictReader(open(ROOT / "data" / "blocks.csv",
                                    newline="", encoding="utf-8")))
    sys.path.insert(0, str(ROOT / "tools"))
    from validate_standards import validate as validate_standards
    std_errs, std_cov = validate_standards(rows)
    if std_errs:
        raise SystemExit("standards/rubrics invalid: " + "; ".join(std_errs[:3]))
    packs = OrderedDict()
    for r in rows:
        packs.setdefault(r["pack"], []).append(r)

    lines = [
        "# Data Quality Dashboard",
        "",
        "Generated by `tools/data_quality.py` from `data/blocks.csv` — never",
        "hand-edited. CI regenerates it on every push and fails on drift, so",
        "this table is always current with the dataset.",
        "",
        f"**{len(rows):,} blocks · {len(packs)} packs · "
        f"{len({(r['pack'], r['track']) for r in rows if r['track']})} tracks · "
        f"{len({r['credential'] for r in rows} - LEVEL_WORDS):,} credentials**",
        "",
        "The known content debt (see the roadmap): band-suffix descriptions",
        "share one sentence across bands with an “— at ‹band›” suffix; the",
        "irregular foundation rows carry structural `code`/`level` but await",
        "authored descriptions. Neither is hidden — both are counted here.",
        "",
        "| Pack | Blocks | Tracks | Desc % | Band-suffix % | Code+level % | Level-word cred % | Min check len |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for name, pr in packs.items():
        n = len(pr)
        tracks = len({r["track"] for r in pr if r["track"]})
        desc = sum(1 for r in pr if r["description"].strip())
        suff = sum(1 for r in pr if SUFFIX.search(r["description"].strip()))
        cl = sum(1 for r in pr if r["code"].strip() and r["level"].strip())
        lw = sum(1 for r in pr if r["credential"].strip() in LEVEL_WORDS)
        minchk = min(len(r["transfer_check"]) for r in pr)
        lines.append(
            f"| {name} | {n} | {tracks} | {100*desc//n}% | {100*suff//n}% "
            f"| {100*cl//n}% | {100*lw//n}% | {minchk} |")

    desc_all = sum(1 for r in rows if r["description"].strip())
    suff_all = sum(1 for r in rows if SUFFIX.search(r["description"].strip()))
    cl_all = sum(1 for r in rows if r["code"].strip() and r["level"].strip())
    # description overrides: rows in an override promotion's pack whose description
    # is that theme's authored sentence for the row's band (see normalize_blocks.py)
    overrides, override_packs = 0, set()
    for p in sorted((ROOT / "data" / "promotions").glob("*.json")):
        spec = json.loads(p.read_text(encoding="utf-8"))
        if spec.get("override") != "band-suffix":
            continue
        bands = {th["theme"]: th["bands"] for t in spec["tracks"] for th in t["themes"]}
        for r in rows:
            if r["pack"] == spec["pack"] and r["theme"] in bands and r["description"].strip() == str(bands[r["theme"]].get(r["grade"], "")).strip():
                overrides += 1
                override_packs.add(r["pack"])
    lw_rows = [r for r in rows if r["credential"].strip() in LEVEL_WORDS]
    lw_tracks = {(r["pack"], r["track"]) for r in lw_rows if r["track"]}
    creds = {r["credential"] for r in rows}
    lines += [
        "",
        f"**Dataset-wide:** descriptions {100*desc_all//len(rows)}% · "
        f"band-suffix {100*suff_all//len(rows)}% · code+level "
        f"{100*cl_all//len(rows)}% · shortest transfer check "
        f"{min(len(r['transfer_check']) for r in rows)} chars.",
        "",
        "## Standards and rubrics",
        "",
        "Standards mappings (`data/standards/*.json`) name the codes a block was",
        "designed against — *cites* — or the performance expectations a track's",
        "blocks practise at a band — *touches*. Neither is an external alignment",
        "review, and every framework carries the caveat to verify codes against the",
        "current document. Rubrics (`data/rubrics/*.json`) give an assessor pass",
        "evidence, failure modes and a note per track. Validated by",
        "`tools/validate_standards.py`.",
        "",
        f"- Blocks carrying at least one standards code: **{std_cov['blocks_covered']:,}** of {len(rows):,} ({100*std_cov['blocks_covered']//len(rows)}%) — "
        + " · ".join(f"{i} ({s}: {n} entries, {c} codes)" for i, s, n, c in std_cov["frameworks"]),
        f"- Tracks with a transfer-check rubric: **{std_cov['tracks_with_rubric']}** of {std_cov['tracks']} ({100*std_cov['tracks_with_rubric']//std_cov['tracks']}%) — the core-spine tracks the Louisiana ledger credits.",
        "",
        "## Description overrides",
        "",
        "The pipeline never overwrites a non-empty source field, with two counted",
        "exceptions. The second (v0.72.0): a promotion declaring",
        "`\"override\": \"band-suffix\"` replaces a band-suffixed description — the",
        "content debt above, and nothing else — with an authored sentence for that",
        "band; the normaliser refuses any other target with the row id.",
        "",
        f"- Rows whose band-suffix description was replaced by an authored band sentence: **{overrides:,}** "
        f"across {len(override_packs)} pack(s) ({', '.join(sorted(override_packs)) or 'none'}).",
        "",
        "## Credential naming",
        "",
        "A credential should name an accomplishment (“Oral Health Peer”), not a",
        "band level. The v0.1.0 legacy import left rows whose `credential` is the",
        "bare word “Practitioner”, so the headline credential count includes it as",
        "if it were a credential. Authoring real names for these tracks is review-",
        "board work (see `docs/GOVERNANCE.md`); `tests/test_platform.py` pins the",
        "scope so it can only shrink.",
        "",
        f"- Rows whose credential is a bare level word: **{len(lw_rows):,}** "
        f"({100*len(lw_rows)//len(rows)}% of the dataset), across "
        f"**{len(lw_tracks)} tracks** in {len({p for p, _ in lw_tracks})} packs.",
        f"- Distinct credential strings: **{len(creds):,}** — of which "
        f"**{len(creds & LEVEL_WORDS)}** {'is a level word' if len(creds & LEVEL_WORDS) == 1 else 'are level words'} "
        f"({', '.join(sorted(creds & LEVEL_WORDS)) or 'none'}), leaving "
        f"**{len(creds - LEVEL_WORDS):,}** real credentials.",
        "",
    ]
    text = "\n".join(lines)
    changed = (not OUT.exists()) or OUT.read_text(encoding="utf-8") != text
    OUT.write_text(text, encoding="utf-8")
    print(f"{'wrote' if changed else 'unchanged'} {OUT.relative_to(ROOT)} "
          f"({len(packs)} packs)")


if __name__ == "__main__":
    main()
