"""The shared runtime every app builder injects (v0.55.0).

Two placeholders in each template:

  __CXHEAD__  (in <head>)  -> the Content-Security-Policy and referrer
                              metas, and the embedded typefaces (@font-face
                              with data: URIs from data/fonts/, so no app
                              makes a third-party request)
  __CXSIM__   (in <body>)  -> the app's runtime globals (CX_APP, CX_PRIVACY),
                              the Simulation Studio engine (tools/sim/engine.js)
                              and the Data & privacy notice (tools/privacy/notice.js)

    from runtime_lib import inject_runtime
    html = inject_runtime(template.replace("__XXDATA__", data), "louisiana")

The CSP is the mechanical form of "nothing leaves the page on its own":
connect-src 'none' makes the browser refuse every fetch, XHR, WebSocket,
beacon and EventSource, whatever any script tries. Inline script and
style are allowed because each app is one file; there is no eval.
"""

import base64
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "data" / "fonts"
ENGINE = ROOT / "tools" / "sim" / "engine.js"
XR = ROOT / "tools" / "xr" / "engine.js"          # v0.69.0: the WebXR view of a studio run
NOTICE = ROOT / "tools" / "privacy" / "notice.js"
PRIVACY = ROOT / "data" / "policy" / "privacy.json"

CSP = ("default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; "
       "img-src data: blob:; font-src data:; media-src data: blob:; manifest-src blob:; "
       "connect-src 'none'; form-action 'none'; base-uri 'none'; object-src 'none'; "
       "frame-src 'none'; worker-src 'none'")

APPS = {
    "education-os":   {"name": "Education OS",   "prefixes": ["aff."],                     "fonts": []},
    "flow-hub":       {"name": "Flow Hub",       "prefixes": ["cxflow."],                  "fonts": ["Archivo", "Instrument Sans", "IBM Plex Mono"]},
    "louisiana":      {"name": "Louisiana",      "prefixes": ["cxla."],  "idb": ["cxla.office", "cxla.ledgerdb"],  "fonts": ["Fraunces", "Instrument Sans", "IBM Plex Mono"]},
    "platform":       {"name": "Platform",       "prefixes": ["cxpx."],                    "fonts": ["Fraunces", "Instrument Sans", "IBM Plex Mono"]},
    "states":         {"name": "States",         "prefixes": ["cxst."],                    "fonts": ["Fraunces", "Instrument Sans", "IBM Plex Mono"]},
    "trades-network": {"name": "Trades Network", "prefixes": ["cxtn."],                    "fonts": ["Fraunces", "Instrument Sans", "IBM Plex Mono"]},
}


def _safe(js):
    return js.replace("</", "<\\/")


def font_faces(families):
    """@font-face rules for the named families, each file embedded once
    (variable families cover a weight range with a single file)."""
    idx = json.loads((FONTS / "fonts.json").read_text(encoding="utf-8"))["fonts"]
    seen = {}
    for f in idx:
        if f["family"] not in families:
            continue
        # Google serves one variable file under several weights; embed each distinct file once
        digest = hashlib.sha256((FONTS / f["file"]).read_bytes()).hexdigest()
        seen.setdefault((f["family"], digest), [f["file"], []])[1].append(f)
    rules = []
    for (family, _), (fn, faces) in seen.items():
        weights = sorted({int(w) for f in faces for w in f["weight"].split()})
        weight = f"{weights[0]} {weights[-1]}" if len(weights) > 1 else str(weights[0])
        data = base64.b64encode((FONTS / fn).read_bytes()).decode("ascii")
        rules.append(
            f"@font-face{{font-family:'{family}';font-style:{faces[0]['style']};font-weight:{weight};"
            f"font-display:swap;src:url(data:font/woff2;base64,{data}) format('woff2');"
            f"unicode-range:{faces[0]['unicode_range']}}}")
    return "\n".join(rules)


def head_snippet(app):
    cfg = APPS[app]
    return (f'<meta http-equiv="Content-Security-Policy" content="{CSP}">\n'
            f'<meta name="referrer" content="no-referrer">\n'
            f'<style data-cx-fonts="{len(cfg["fonts"])}">\n{font_faces(cfg["fonts"])}\n</style>')


def body_snippet(app, extra_js=""):
    cfg = APPS[app]
    version = (ROOT / "VERSION").read_text().strip()
    privacy = json.loads(PRIVACY.read_text(encoding="utf-8"))
    globals_js = ("window.CX_APP=" + json.dumps({"id": app, "name": cfg["name"], "version": version,
                                                  "prefixes": cfg["prefixes"], "idb": cfg.get("idb", [])}, ensure_ascii=False)
                  + ";\nwindow.CX_PRIVACY=" + json.dumps(privacy, ensure_ascii=False) + ";\n" + extra_js)
    return ("<script>/* CX shared runtime v" + version + " — generated by tools/runtime_lib.py; rebuild, never edit */\n"
            + _safe(globals_js) + "</script>\n"
            + "<script>" + _safe(ENGINE.read_text(encoding="utf-8")) + "</script>\n"
            + "<script>" + _safe(XR.read_text(encoding="utf-8")) + "</script>\n"
            + "<script>" + _safe(NOTICE.read_text(encoding="utf-8")) + "</script>")


def inject_runtime(html, app, extra_js=""):
    for ph in ("__CXHEAD__", "__CXSIM__"):
        if ph not in html:
            raise SystemExit(f"{app}: template is missing the {ph} placeholder")
    if "<script>__CXSIM__" in html:
        raise SystemExit(f"{app}: __CXSIM__ must stand alone — the runtime brings its own <script> tags")
    return html.replace("__CXHEAD__", head_snippet(app)).replace("__CXSIM__", body_snippet(app, extra_js))
